### ISSUE TITLE
SMT-COMP references

### ISSUE THREAD

**Issue by andrikos** [bitwuzla/bitwuzla#102]
Hi, it seems that the links for SMT-COMP in the NEWS section, e.g. http://www.smt-comp.org/2023, on the project's homepage are outdated. 
The old site in http://smt-comp.org has been moved to http://smt-comp.github.io

Thanks!

**Comment by mpreiner** [comment]
Thanks for reporting. This is now fixed with bitwuzla/bitwuzla.github.io@e1bf2a1c419e37f3f54d32c8c779907131ed0df5
