### ISSUE TITLE
Memory Limit Not Working (Python Bindings)?

### ISSUE THREAD

**Issue by sunil10110** [bitwuzla/bitwuzla#105]
Hi - I am using Python bindings and WSL (windows subsystem for Linux) and the memory limit doesn't seem to be enforced:
e.g
options.set(bitwuzla.Option.MEMORY_LIMIT,16384)

For the problem I am working on, the desired memory greatly exceeds this so the process gets killed. 

I'm not sure if it has to do with the WSL usage or if this is a real issue.   

Thanks

**Comment by mpreiner** [comment]
Do you have an example Python script that we an use to reproduce the behavior?

**Comment by mpreiner** [comment]
It could be that this was fixed with https://github.com/bitwuzla/bitwuzla/commit/d711df957ab56259624fbb98597f8234a355485c.

**Comment by mpreiner** [comment]
Feel free to reopen the issue if this doesn't fix your problem.
