### ISSUE TITLE
Installing issue related to downloading downloading symfpu

### ISSUE THREAD

**Issue by Abhinandan-Pal** [bitwuzla/bitwuzla#108]
I obtained the following error trace on Pop!_OS 22.04 LTS. The file mentioned in the trace is attached.

`/bitwuzla$ ./configure.py
-- meson setup build
The Meson build system
Version: 1.3.2
Source dir: /mnt/C08CE0398CE02C1A/PhD/First_Year/LiveNeuron/Dependencies/bitwuzla
Build dir: /mnt/C08CE0398CE02C1A/PhD/First_Year/LiveNeuron/Dependencies/bitwuzla/build
Build type: native build
Project name: bitwuzla
Project version: 0.4.0-dev
C compiler for the host machine: cc (gcc 11.4.0 "cc (Ubuntu 11.4.0-1ubuntu1~22.04) 11.4.0")
C linker for the host machine: cc ld.bfd 2.38
C++ compiler for the host machine: c++ (gcc 11.4.0 "c++ (Ubuntu 11.4.0-1ubuntu1~22.04) 11.4.0")
C++ linker for the host machine: c++ ld.bfd 2.38
Host machine cpu family: x86_64
Host machine cpu: x86_64
Found pkg-config: YES (/usr/bin/pkg-config) 0.29.2
Run-time dependency gmp found: YES 6.2.1
Has header "cadical.hpp" : NO 
Found CMake: /usr/bin/cmake (3.22.1)
Run-time dependency cadical found: NO (tried pkgconfig and cmake)
Looking for a fallback subproject for the dependency cadical
Downloading cadical source from https://github.com/arminbiere/cadical/archive/rel-1.7.4.tar.gz
Downloading file of unknown size.

Executing subproject cadical 

cadical| Project name: cadical
cadical| Project version: 1.7.4
cadical| C++ compiler for the host machine: c++ (gcc 11.4.0 "c++ (Ubuntu 11.4.0-1ubuntu1~22.04) 11.4.0")
cadical| C++ linker for the host machine: c++ ld.bfd 2.38
cadical| Configuring build.hpp using configuration
cadical| Checking for function "getc_unlocked" : YES
cadical| Build targets in project: 1
cadical| Subproject cadical finished.

Dependency cadical from subproject subprojects/cadical-rel-1.7.4 found: YES 1.7.4
Has header "kissat.h" : NO 
Run-time dependency kissat found: NO (tried pkgconfig and cmake)
Run-time dependency symfpu found: NO (tried pkgconfig and cmake)
Looking for a fallback subproject for the dependency symfpu
Initialized empty Git repository in /mnt/C08CE0398CE02C1A/PhD/First_Year/LiveNeuron/Dependencies/bitwuzla/subprojects/symfpu/.git/
fatal: detected dubious ownership in repository at '/mnt/C08CE0398CE02C1A/PhD/First_Year/LiveNeuron/Dependencies/bitwuzla/subprojects/symfpu'
To add an exception for this directory, call:

	git config --global --add safe.directory /mnt/C08CE0398CE02C1A/PhD/First_Year/LiveNeuron/Dependencies/bitwuzla/subprojects/symfpu

src/meson.build:37:13: ERROR: Git command failed: ['/usr/bin/git', 'remote', 'add', 'origin', 'https://github.com/martin-cs/symfpu.git']

A full log can be found at /mnt/C08CE0398CE02C1A/PhD/First_Year/LiveNeuron/Dependencies/bitwuzla/build/meson-logs/meson-log.txt
-- compile Bitwuzla with: cd build && meson compile
obi@pop-os:/mnt/C08CE0398CE02C1A/PhD/First_Year/LiveNeuron/Dependencies/bitwuzla$ cd build && ninja install
ninja: error: loading 'build.ninja': No such file or directory
[meson-log.txt](https://github.com/bitwuzla/bitwuzla/files/14576690/meson-log.txt)
`

**Comment by mpreiner** [comment]
Is `/mnt/C08CE0398CE02C1A/` supposed to be a network mount or anything like that? Do you have the same issue if you try this e.g. in `/tmp/`?

**Comment by Abhinandan-Pal** [comment]
The path ```shell /mnt/C08CE0398CE02C1A/```   is just a partition on the hard drive. While attempting to install at ```/tmp/```resolves the current issue, it triggers a different one, indicating that the module 'mesonbuild' is not found, despite being importable in an interactive Python environment.

```shell
obi@pop-os:/tmp/bitwuzla/build$ ninja install
[0/1] Installing files.
Installing subdir /tmp/bitwuzla/include/bitwuzla to /usr/local/include/bitwuzla
Installation failed due to insufficient permissions.
Attempt to use /usr/bin/sudo to gain elevated privileges? [y/n] y
Traceback (most recent call last):
  File "/home/obi/.local/bin/meson", line 5, in <module>
    from mesonbuild.mesonmain import main
ModuleNotFoundError: No module named 'mesonbuild'
FAILED: meson-internal__install 
/home/obi/.local/bin/meson install --no-rebuild
ninja: build stopped: subcommand failed.
obi@pop-os:/tmp/bitwuzla/build$ python3
Python 3.10.6 (main, May 29 2023, 11:10:38) [GCC 11.3.0] on linux
Type "help", "copyright", "credits" or "license" for more information.
>>> import mesonbuild
>>> from mesonbuild.mesonmain import main
>>> 2
2

```

**Comment by mpreiner** [comment]
Do you have the same issue with `pip3 install .`?

**Comment by Abhinandan-Pal** [comment]
``` pip3 install . ```  does work! thanks
