### ISSUE TITLE
Solving limits

### ISSUE THREAD

**Issue by SweetVishnya** [bitwuzla/bitwuzla#11]
Hi!

Is there a way to specify timeout and memory limit for query?

**Comment by SweetVishnya** [comment]
I found an [example](https://github.com/bitwuzla/bitwuzla/blob/main/src/api/python/pybitwuzla.pyx#L401). Should I configure termination function?

**Comment by SweetVishnya** [comment]
And who calls this termination function and how often?

P.S. A minimal example is much appreciated.

**Comment by SweetVishnya** [comment]
We figured it out)

**Comment by aniemetz** [comment]
Hi @SweetVishnya, sorry for the late reply, Mathias and I were both on vacation. Do you still need help?

**Comment by SweetVishnya** [comment]
@aniemetz, we already supported solving timeout [this](https://github.com/JonathanSalwan/Triton/pull/1062/files#diff-f6d0c1c9dfd4aa4396cfcf9daca05db7f04d1e06231e5ab9ab7b55ddc33603e4R24) way.

We still have some further questions.

Will Biwuzla support quantifiers ([forall](quantifiers))?

Moreover, I wrote an email to Mathias about SMT-COMP config. I'll copy it here:

We finally managed to support Bitwuzla in [Triton](https://github.com/JonathanSalwan/Triton/pull/1062). It actually provides [Sydr](https://arxiv.org/abs/2011.09269) 2-6x speedup. Could you shed some light on the best Bitwuzla setup for QF_BV? Did you use CaDiCaL solver to win latest SMT-COMP? Which options should be also enabled for better results?

**Comment by mpreiner** [comment]
Bitwuzla will support quantifiers in the future, we are currently working on a big refactor of the quantifiers code.

About the Bitwuzla SMT-COMP configuration: You can find the scripts to build the configurations for SMT-COMP here: https://github.com/bitwuzla/bitwuzla/tree/main/contrib/smtcomp

In the last competitions we used CaDiCaL. The best configuration depends on what your application is. Are you using Bitwuzla incrementally? You can look up the options used for `--smt-comp` [here](https://github.com/bitwuzla/bitwuzla/blob/main/src/parser/bzlasmt2.c#L471)

**Comment by SweetVishnya** [comment]
Thanks for the tips. We use Bitwuzla in a non-incremental mode.
