### ISSUE TITLE
Does the solver have a multithreading option?

### ISSUE THREAD

**Issue by jiahaoxiang2000** [bitwuzla/bitwuzla#111]
I am currently using Bitwuzla for some cryptographic S-box searches. Previously, I used the STP SMT solver, which supports CryptoMiniSat and multithreading. I found the multithreading feature particularly useful as it significantly improved the speed of my computations. Now, I am interested in learning how to use the multithreading feature with Bitwuzla, as using a single thread is too slow for my needs. I appreciate any assistance you can provide with this seemingly simple problem.

**Comment by mpreiner** [comment]
Bitwuzla does not yet support multithreading, but it's on our TODO list, same as for adding CryptoMiniSat. We'll keep you posted.

**Comment by jiahaoxiang2000** [comment]
> Bitwuzla does not yet support multithreading, but it's on our TODO list, same as for adding CryptoMiniSat. We'll keep you posted.

It's great to hear that Bitwuzla will soon support multithreading. Thank you for your hard work.

**Comment by mpreiner** [comment]
@jiahaoxiang2000 do you have benchmarks that you can share with us?

**Comment by jiahaoxiang2000** [comment]
> @jiahaoxiang2000 do you have benchmarks that you can share with us?

Sure, I'm happy to do this. Next time I conduct the experiment, I'll record the multithreading speed time.

**Comment by jiahaoxiang2000** [comment]
By solving the [qarmav2_inverse.txt](https://github.com/bitwuzla/bitwuzla/files/15400085/qarmav2_inverse.txt) file, these are the comparison times between multithreading and single-threading:

- Multithreading with [stp](https://github.com/stp/stp): 
    ```
    stp --SMTLIB2 ./smt2/qarmav2_inverse.smt2 --threads 30 --cryptominisat -n
    ```
    Total execution time: **1137.86** seconds.

- Single-threaded solver using `bitwuzla.check_sat()` in Python:
    Total execution time: **290298.56** seconds.

**Comment by jiahaoxiang2000** [comment]
@mpreiner By solving the [qarmav2_inverse.txt](https://github.com/bitwuzla/bitwuzla/files/15400085/qarmav2_inverse.txt) file, these are the comparison times between multithreading and single-threading:

- Multithreading with  [stp](https://github.com/stp/stp): 
    ```
    stp --SMTLIB2 ./smt2/qarmav2_inverse.smt2 --threads 30 --cryptominisat -n
    ```
    Total execution time: **1137.86** seconds.

- Single-threaded solver using `bitwuzla.check_sat()` in Python:
    Total execution time: **290298.56** seconds.

**Comment by jiahaoxiang2000** [comment]
@mpreiner By solving the [qarmav2_inverse.txt](https://github.com/bitwuzla/bitwuzla/files/15400085/qarmav2_inverse.txt) file, these are the comparison times between multithreading and single-threading:

- Multithreading with [`stp`](https://github.com/stp/stp): 
    ```
    stp --SMTLIB2 ./smt2/qarmav2_inverse.smt2 --threads 30 --cryptominisat -n
    ```
    Total execution time: **1137.86** seconds.

- Single-threaded solver using `bitwuzla.check_sat()` in Python:
    Total execution time: **290298.56** seconds.

Solver Environment:
- OS: Ubuntu 22.04
- Kernel: x86_64 Linux 6.5.0-28-generic
- CPU: Intel Core i9-14900KF @ 32x 5.7GHz

**Comment by mpreiner** [comment]
@jiahaoxiang2000 CryptoMiniSat support is now merged to main. You can specify the number of threads with option `-j/--nthreads`.

**Comment by jiahaoxiang2000** [comment]
Big thanks to @mpreiner  for the support and guidance in solving the issue! 👍
