### ISSUE TITLE
Weird output on check-sat with kissat

### ISSUE THREAD

**Issue by bruderj15** [bitwuzla/bitwuzla#119]
Hello all.

When running version 0.5 with `bitwuzla --sat-solver-kissat` and below input:
```smt2
(set-option :produce-models true)
(set-logic QF_BV)
(declare-fun var_1 () (_ BitVec 8))
(check-sat)
```
I get the following response:
```bash
c  seconds switched conflicts irredundant variables
c         MB reductions redundant  trail remaining
c          level restarts   binary    glue
c
c *  0.00  7 0 0 0  0   0   0   0  0 0% 0  0 0%
c {  0.00  7 0 0 0  0   0   0   0  0 0% 0  0 0%
c }  0.00  7 0 0 0  0   0   0   0  0 0% 0  0 0%
c 1  0.00  7 0 0 0  0   0   0   0  0 0% 0  0 0%
sat
```

What is this supposed to tell me? Could not find anything in the docs.
Is there a way to get rid of this message?
When using Cadical as SAT-Solver, the response is just `sat`, as expected.

Thanks in advance!

**Comment by mpreiner** [comment]
This is output from Kissat, but should actually be silenced since we are setting the `quiet` option to `1`. I can't reproduce this with current main. With `--sat-solver=kissat` I only get:

```
bitwuzla issue119.smt2  --sat-solver=kissat
sat
```

**Comment by mpreiner** [comment]
@bruderj15 Can you post the output of the configure stage for this build?

**Comment by mpreiner** [comment]
Ah yes, that makes sense. I think the default build of kissat is more verbose.
