### ISSUE TITLE
AigCnfEncoder::_encode Timeout

### ISSUE THREAD

**Issue by cknizek** [bitwuzla/bitwuzla#122]
Hi Bitwuzla team,

I'm contributing to [a project that uses counterexample-guided synthesis](https://github.com/uwsampl/lakeroad), and Bitwuzla is one of the solvers we use most. 

However, starting with Bitwuzla commit `e211881f70b7030a9a2ba25fbfdd2d2fa6a0cf44` [1], certain integration tests for the project begin to fail. 

The previous commit, `9e5d7d82b0a0bfd3dc838eb3c3936acad500dc97` [2], passes all the integration tests succesfully.

As a result, we haven't been able to update Bitwuzla to the more recent versions.

The issue seems to be that in the `AigCnfEncoder::_encode` subroutine in `src/lib/bitblast/aig/aif_cnf.cpp`, I think either the AIG is being traversed for a very long time when building the CNF (either in `AigCnfEncoder::_encode` or in `is_ite`).

There is a particular segment in `aig_cnf.cpp` that seems to have a significant effect on the issue. To be more specific, when the check for `is_ite(*cur, children)` is removed, the counter-example guided synthesis using Bitwuzla succeeds, with `unsat`.

I'm not sure if this is related to the other issue I created (https://github.com/bitwuzla/bitwuzla/issues/121) because, in this case, the SMT2 files being generated time-out for other solvers as well. 

I will follow up with this issue and see if I can identify further what's going on, but I just wanted to let you all know about the issue

Thanks,
Colin

[1] [lib: bitblast: Add native ite CNF encoding.](https://github.com/bitwuzla/bitwuzla/commit/e211881f70b7030a9a2ba25fbfdd2d2fa6a0cf44)

[2] [lib: aignode: Allow inlining of is_null() and is_negated().](https://github.com/bitwuzla/bitwuzla/commit/9e5d7d82b0a0bfd3dc838eb3c3936acad500dc97)

[3] [Bitwuzla_BeforeAfter_CNF_Encode_Update.zip](https://github.com/user-attachments/files/16897967/Bitwuzla_BeforeAfter_CNF_Encode_Update.zip)
- SMT2 file generated before CNF Encoder update (unsat) 
- SMT2 file generated after CNF encoder update (hangs indefinitely)

**Comment by mpreiner** [comment]
This is related to #121. It is not stuck in the CNF encoder. The Before version produces a very simple CNF, whereas the After version is hard for the SAT Solver to solve. Both versions are solved immediately with the branch we mentioned in #121.

**Comment by cknizek** [comment]
Shoot, my apologies. I'm going to close this issue because:
- It's a duplicate
- The problem is not related to the CNF encoder
- It's solved by the branch mentioned in #121 

Thanks for being so responsive!

**Comment by mpreiner** [comment]
@cknizek If you have more of these performance regressions, keep posting them in #121 and we'll check whether this will be fixed with our branch. These performance regression reports are very much appreciated. Thank you!
