### ISSUE TITLE
Disable the INCREMENTAL option

### ISSUE THREAD

**Issue by zeroEuphemia** [bitwuzla/bitwuzla#125]
Hello! The News mentions, "Incremental solving is now always enabled and thus the option INCREMENTAL is removed." Is there any way to disable the INCREMENTAL option in the current version? I would like the solver to forget the information from the previous solving session each time I call check_sat. Thank you!

**Comment by mpreiner** [comment]
I think you misunderstand what incremental vs. non-incremental does. What you want is resetting the solver after a check-sat call, which you can do with the `(reset)` command in SMT-LIB. If you are using Bitwuzla via the API you can just create a new solver instance.
