### ISSUE TITLE
Refutational soundness bug on QF_UFBV instance

### ISSUE THREAD

**Issue by fwangdo** [bitwuzla/bitwuzla#131]
Greetings,
For this instance, a refutational soundness bug occurred.
We tried to minimize the bug instance with ddsmt however, it failed to reduce the size of the instance. Therefore, we attach the instance in this article.
(we checked that the instance had a solution through cvc5.)
```
$ cvc5 ./bug.smt2 --produce-model --check-models
sat
 
$ ./bitwuzla ./bug.smt2
unsat
[error] ./bug.smt2:891:11: 'unsat' but status is 'sat'
```
[bug.txt](https://github.com/user-attachments/files/17625851/bug.txt)

commit version: [2b3d69a](https://github.com/bitwuzla/bitwuzla/commit/2b3d69a797e5c60f83a9f8fc200f03fadcf7f4ad)
release version: 0.6.0

**Comment by BrunoDutertre** [comment]
Here's a reduced example:
```
(set-logic QF_BV)
(declare-fun z () (_ BitVec 1))
(assert (bvslt (bvor (bvmul #b10 ((_ zero_extend 1) z)) (concat #b1 (bvshl #b1 z))) #b00))
(check-sat)
```

This is a bug in the `BV_AND_CONCAT` rewrite.
