### ISSUE TITLE
kissat bug

### ISSUE THREAD

**Issue by Gy-Hu** [bitwuzla/bitwuzla#132]
I wanted to bring to your attention an issue I encountered while configuring Bitwuzla with the Kissat option. When I open it during the solving process, it generates some "false" counterexamples where all inputs are 0. Could there be a compatibility issue between Bitwuzla and Kissat? Any insights you could provide would be greatly appreciated. Thank you!

**Comment by Gy-Hu** [comment]
Thank you for your support! Since all the test cases are in an industrial environment, I will create some hand-crafted cases to reproduce this issue. If it exists, I will open this issue again.

**Comment by Gy-Hu** [comment]
@mpreiner  Hi Mathias, I reproduce the bug, 
[bitwuzla_bug_.txt](https://github.com/user-attachments/files/17726058/bitwuzla_bug_.txt)
Rename this to .btor2

I put the command to reproduce this
![image](https://github.com/user-attachments/assets/f4522396-d92b-4391-9f8b-fc7a1c525901)

My bitwuzla version : 0.5.0-dev-main@c55191c9
the kissat I configure using  `./configure.py --kissat` , the dependecy seems to pull automatically in subprojects/packagecache/kissat-rel-4.0.1.tar.gz

Could you help to handle this bug? Thanks a lot!

**Comment by Gy-Hu** [comment]
It seems using different rewrite levels will affect this issue as well?
<img width="1156" alt="image" src="https://github.com/user-attachments/assets/9f805cbc-2a64-489b-8ac9-565f253cfa59">

**Comment by mpreiner** [comment]
The issue is that Kissat does not support incremental solving. This is now properly guarded in non-debug builds on main.

**Comment by Gy-Hu** [comment]
@mpreiner Hi Mathias, I noticed the previous version of Bitwuzla had an option to enable or disable the 'incremental solving' feature. Do you plan to add this feature back? Thank you!

**Comment by mpreiner** [comment]
There are no plans to add this option back. In what sense would that be useful in your case?

**Comment by Gy-Hu** [comment]
@mpreiner We have noticed significant improvements in Kissat version 4.0.1. However, due to the incremental solving feature in Bitwuzla, we are unable to use Kissat as the backend for this advanced SMT solver. Therefore, adding an option to disable incremental solving would enable us to take full advantage of the latest features of both Kissat and Bitwuzla.

**Comment by mpreiner** [comment]
I think there is a misunderstanding of what the incremental option did. It configured the solver for **incremental SMT queries**. However, Bitwuzla uses SAT solvers incrementally for the majority of supported theories, even for non-incremental SMT queries. Kissat can only be used for problems where Bitwuzla does not require incremental SAT solving. This only applies to problems in the QF_BV logic, and even then only if features that require incremental SAT solving are not enabled (e.g. unsat cores, unsat assumptions, abstraction,...). Adding the incremental option back would not allow you to use Kissat more often.

**Comment by aniemetz** [comment]
Just for the sake of completeness, Bitwuzla is **always** configured for **incremental SMT solving**, that is why option `--incremental` was removed (it would be a noop).
