### ISSUE TITLE
UBSan errors

### ISSUE THREAD

**Issue by fvrmatteo** [bitwuzla/bitwuzla#136]
Hi!

I'm linking Bitwuzla as a static library in one of my projects and noticed that, when built with the `ASan` + `UBSan` options, it runs into several runtime undefined behaviour errors.

Therefore I tried building the `bitwuzla` binary with the following options and verified if the errors would replicate (forcing `b_lundef=false` as per Meson warning and using `clang-19`):
```
python3 configure.py --prefix "$(pwd)/install" --assertions --asan --ubsan --no-testing --no-unit-testing debugoptimized
ninja -C build install
```
The user defined options are:
```
b_lundef    : false
b_ndebug    : false
b_sanitize  : address,undefined
buildtype   : debugoptimized
prefix      : /Users/matteo/Documents/bitwuzla/install
testing     : disabled
unit_testing: disabled
```
The following logs come from an example execution: [bitwuzla_ubsan_clang.19.1.3.log](https://github.com/user-attachments/files/17692594/bitwuzla_ubsan_clang.19.1.3.log)

Are the `ASan` and `UBSan` options ever used for testing and is there any interest in tracking down and fixing these kinds of undefined behaviours?

On my side I only tried something as trivial as enforcing the class/struct alignment via `__attribute__((aligned(B)))`, but it doesn't seem to be enough to solve the issues.

**Note**: Some errors come from the LLVM 19.1.3 C++ STL, but the majority are from Bitwuzla structures.

**Comment by mpreiner** [comment]
@fvrmatteo Thanks! We are aware of these issues and are working on fixing them.

**Comment by fvrmatteo** [comment]
Thanks for the confirmation @mpreiner!

I'll happily do more UBSan testing when the fixes will be available. If it's OK with you, I think we can keep the issue open until a fix lands in the `main` branch, just in case someone else will notice the same (since my previous search in the GitHub Issues didn't show any UBSan reference).

**Comment by mpreiner** [comment]
@fvrmatteo All ubsan and asan errors found with gcc/clang on Linux are now fixed on main. Note that errors from third-party libraries are still present (I found one issue in CaDiCaL 1.7.4).

**Comment by mpreiner** [comment]
@fvrmatteo thanks for confirming!
