### ISSUE TITLE
Export the SMT formula when --lang=btor2

### ISSUE THREAD

**Issue by Gy-Hu** [bitwuzla/bitwuzla#142]
Hi, I noticed that the new version of Bitwuzla includes a command-line option called `--pp-only`, which seems to be able to dump the preprocessed formula into a new formula. When I used it with SMT-LIB2 files, it worked well, and the command `--pp-only -p` generated the new SMT-LIB2 file smoothly. This is useful for me because I want to use the preprocessed SMT-LIB2 as input for other SMT solvers at the same time when solving.

However, I found that it doesn't produce any output when I input a BTOR2 file. Is this the expected behavior? I would like a function that can convert BTOR2 (not related to model checking problems) to SMT-LIB2. Regardless of whether I use `-p` or `--pp-only -p`, I cannot see the SMT-LIB2 formula or the processed SMT-LIB2 formula. Are there any plans to add this functionality?

I used:
```
 ./src/main/bitwuzla --pp-only -p --bv-solver bitblast --lang btor2 ../bitwuzla_bug.btor2
```
I got
```
(set-logic ALL)
(check-sat)
(exit)
```

**Comment by mpreiner** [comment]
This should only happen if preprocessing can simplify the problem to true (or false if `(assert false)` is added as assertion).

**Comment by Gy-Hu** [comment]
Great! Thank you! I will try more cases to verify that. So, Bitwuzla does support converting BTOR2 (without states) to SMT-LIB2 naturally, right?

**Comment by mpreiner** [comment]
> Great! Thank you! I will try more cases to verify that. So, Bitwuzla does support converting BTOR2 (without states) to SMT-LIB2 naturally, right?

Yes, that's correct. The supported input languages are BTOR2 and SMT2, output language is SMT2 only.

**Comment by Gy-Hu** [comment]
Awesome, I close this issue until I find the cases (btor2->smt2) that not as expected (hints of loopholes)

**Comment by Gy-Hu** [comment]
Hi @mpreiner, I'm still a bit confused about using `-p` for the btor2 file (without states) that I've attached. According to your response, `bitwuzla_print_test_pass1` and `bitwuzla_print_test_fail1` should yield different SMT formula dumps, even if they can be rewritten to a constant value. However, their dumped SMT-LIB2 formulas appear identical. Am I misunderstanding the command?

[bitwuzla_print_test_fail1.txt](https://github.com/user-attachments/files/17896055/bitwuzla_print_test_fail1.txt)
[bitwuzla_print_test_pass1.txt](https://github.com/user-attachments/files/17896056/bitwuzla_print_test_pass1.txt)


<img width="1021" alt="image" src="https://github.com/user-attachments/assets/19e39a13-3273-4e43-9e50-31086aea946c">

**Comment by mpreiner** [comment]
Ah ok, now I understand what you are doing here. In both input files you have safety properties specified (bad). In this case Bitwuzla is in a different mode: It will check each property with an incremental query and it will not properly print the queries for each property.

**Comment by Gy-Hu** [comment]
Great! Now I successfully dump the formula. Thanks a lot!

**Comment by Gy-Hu** [comment]
By the way, I noticed that Boolector has the functionality to dump AIGER model. Does Bitwuzla have any future plans to support that?

**Comment by mpreiner** [comment]
> By the way, I noticed that Boolector has the functionality to dump AIGER model. Does Bitwuzla have any future plans to support that?

Yes, this is on our TODO list.
