### ISSUE TITLE
Python bindings failing to build

### ISSUE THREAD

**Issue by hanansoicher** [bitwuzla/bitwuzla#148]
This is likely just a setup issue on my part I'm attempting to use bitwuzla's python bindings as a dependency to another dependency to a project I'm working on for school that I really need to get done and am not having success getting the bindings to build. I'm using WSL with Ubuntu on my windows laptop with python 3.10 (I was originally using 3.12 but the other dependency was most recently tested on 3.10 so I switched to that, but these errors were occurring for both), gcc/g++ 11.4.0 (Tried v13 as well), and cython 3.0.11. I am successfully building the program with "./configure.py --python"
but "ninja python-bindings" fails with errors such as the following, I would very much appreciate any support I could get, I can provide more information if I get a response: 

/bitwuzla/build$ ninja python-bindings
[0/199] Generating external project subprojects/gmp-6.3.0/gmp-6.3.0
[104/199] Compiling C++ object src/api/python/bitwuzla.cpython-310-x86_64-linux-gnu.so.p/meson-generated_src_api_python_bitwuzla.pyx.cpp.o
FAILED: src/api/python/bitwuzla.cpython-310-x86_64-linux-gnu.so.p/meson-generated_src_api_python_bitwuzla.pyx.cpp.o 
c++ -Isrc/api/python/bitwuzla.cpython-310-x86_64-linux-gnu.so.p -Isrc/api/python -I../src/api/python -I../include -Isrc/lib -I../src/lib -I/usr/include/python3.10 -fvisibility=hidden -fvisibility-inlines-hidden -fdiagnostics-color=always -DNDEBUG -D_FILE_OFFSET_BITS=64 -Wall -Winvalid-pch -Wextra -Wpedantic -std=c++17 -O3 -fPIC -MD -MQ src/api/python/bitwuzla.cpython-310-x86_64-linux-gnu.so.p/meson-generated_src_api_python_bitwuzla.pyx.cpp.o -MF src/api/python/bitwuzla.cpython-310-x86_64-linux-gnu.so.p/meson-generated_src_api_python_bitwuzla.pyx.cpp.o.d -o src/api/python/bitwuzla.cpython-310-x86_64-linux-gnu.so.p/meson-generated_src_api_python_bitwuzla.pyx.cpp.o -c src/api/python/bitwuzla.cpython-310-x86_64-linux-gnu.so.p/src/api/python/bitwuzla.pyx.cpp
src/api/python/bitwuzla.cpython-310-x86_64-linux-gnu.so.p/src/api/python/bitwuzla.pyx.cpp: In function ‘PyObject* __pyx_pf_8bitwuzla_4Term_18symbol(__pyx_obj_8bitwuzla_Term*)’:
src/api/python/bitwuzla.cpython-310-x86_64-linux-gnu.so.p/src/api/python/bitwuzla.pyx.cpp:12767:55: error: no matching function for call to ‘std::__cxx11::basic_string<char>::basic_string(__Pyx_FakeReference<std::reference_wrapper<const std::__cxx11::basic_string<char> > >&)’
12767 |     __pyx_t_4 = __Pyx_decode_cpp_string(((std::string)__pyx_t_3), 0, PY_SSIZE_T_MAX, NULL, NULL, NULL); if (unlikely(!__pyx_t_4)) __PYX_ERR(0, 382, __pyx_L1_error)
      |                                                       ^~~~~~~~~
In file included from /usr/include/c++/11/string:55,
                 from /usr/include/c++/11/bits/locale_classes.h:40,
                 from /usr/include/c++/11/bits/ios_base.h:41,
                 from /usr/include/c++/11/ios:42,
                 from src/api/python/bitwuzla.cpython-310-x86_64-linux-gnu.so.p/src/api/python/bitwuzla.pyx.cpp:1237:
/usr/include/c++/11/bits/basic_string.h:664:9: note: candidate: ‘template<class _Tp, class> std::__cxx11::basic_string<_CharT, _Traits, _Alloc>::basic_string(const _Tp&, const _Alloc&) [with _Tp = _Tp; <template-parameter-2-2> = <template-parameter-1-2>; _CharT = char; _Traits = std::char_traits<char>; _Alloc = std::allocator<char>]’
  664 |         basic_string(const _Tp& __t, const _Alloc& __a = _Alloc())
      |         ^~~~~~~~~~~~
/usr/include/c++/11/bits/basic_string.h:664:9: note:   template argument deduction/substitution failed:
In file included from /usr/include/c++/11/bits/move.h:57,
                 from /usr/include/c++/11/bits/stl_pair.h:59,
                 from /usr/include/c++/11/bits/stl_algobase.h:64,
                 from /usr/include/c++/11/bits/specfun.h:45,
                 from /usr/include/c++/11/cmath:1935,
                 from /usr/include/c++/11/math.h:36,
                 from /usr/include/python3.10/pyport.h:210,
                 from /usr/include/python3.10/Python.h:50,
                 from src/api/python/bitwuzla.cpython-310-x86_64-linux-gnu.so.p/src/api/python/bitwuzla.pyx.cpp:16:
/usr/include/c++/11/type_traits: In substitution of ‘template<bool _Cond, class _Tp> using enable_if_t = typename std::enable_if::type [with bool _Cond = false; _Tp = void]’:
/usr/include/c++/11/bits/basic_string.h:125:8:   required by substitution of ‘template<class _CharT, class _Traits, class _Alloc> template<class _Tp, class _Res> using _If_sv = std::enable_if_t<std::__and_<std::is_convertible<const _Tp&, std::basic_string_view<_CharT, _Traits> >, std::__not_<std::is_convertible<const _Tp*, const std::__cxx11::basic_string<_CharT, _Traits, _Alloc>*> >, std::__not_<std::is_convertible<const _Tp&, const _CharT*> > >::value, _Res> [with _Tp = __Pyx_FakeReference<std::reference_wrapper<const std::__cxx11::basic_string<char> > >; _Res = void; _CharT = char; _Traits = std::char_traits<char>; _Alloc = std::allocator<char>]’
/usr/include/c++/11/bits/basic_string.h:662:30:   required from here
/usr/include/c++/11/type_traits:2579:11: error: no type named ‘type’ in ‘struct std::enable_if<false, void>’
 2579 |     using enable_if_t = typename enable_if<_Cond, _Tp>::type;
      |           ^~~~~~~~~~~
In file included from /usr/include/c++/11/string:55,
                 from /usr/include/c++/11/bits/locale_classes.h:40,
                 from /usr/include/c++/11/bits/ios_base.h:41,
                 from /usr/include/c++/11/ios:42,
                 from src/api/python/bitwuzla.cpython-310-x86_64-linux-gnu.so.p/src/api/python/bitwuzla.pyx.cpp:1237:
/usr/include/c++/11/bits/basic_string.h:653:9: note: candidate: ‘template<class _Tp, class> std::__cxx11::basic_string<_CharT, _Traits, _Alloc>::basic_string(const _Tp&, std::__cxx11::basic_string<_CharT, _Traits, _Alloc>::size_type, std::__cxx11::basic_string<_CharT, _Traits, _Alloc>::size_type, const _Alloc&) [with _Tp = _Tp; <template-parameter-2-2> = <template-parameter-1-2>; _CharT = char; _Traits = std::char_traits<char>; _Alloc = std::allocator<char>]’
  653 |         basic_string(const _Tp& __t, size_type __pos, size_type __n,
      |         ^~~~~~~~~~~~
/usr/include/c++/11/bits/basic_string.h:653:9: note:   template argument deduction/substitution failed:
src/api/python/bitwuzla.cpython-310-x86_64-linux-gnu.so.p/src/api/python/bitwuzla.pyx.cpp:12767:55: note:   candidate expects 4 arguments, 1 provided
12767 |     __pyx_t_4 = __Pyx_decode_cpp_string(((std::string)__pyx_t_3), 0, PY_SSIZE_T_MAX, NULL, NULL, NULL); if (unlikely(!__pyx_t_4)) __PYX_ERR(0, 382, __pyx_L1_error)
      |                                                       ^~~~~~~~~
In file included from /usr/include/c++/11/string:55,
                 from /usr/include/c++/11/bits/locale_classes.h:40,
                 from /usr/include/c++/11/bits/ios_base.h:41,
                 from /usr/include/c++/11/ios:42,
                 from src/api/python/bitwuzla.cpython-310-x86_64-linux-gnu.so.p/src/api/python/bitwuzla.pyx.cpp:1237:
/usr/include/c++/11/bits/basic_string.h:638:9: note: candidate: ‘template<class _InputIterator, class> std::__cxx11::basic_string<_CharT, _Traits, _Alloc>::basic_string(_InputIterator, _InputIterator, const _Alloc&) [with _InputIterator = _InputIterator; <template-parameter-2-2> = <template-parameter-1-2>; _CharT = char; _Traits = std::char_traits<char>; _Alloc = std::allocator<char>]’
  638 |         basic_string(_InputIterator __beg, _InputIterator __end,
      |         ^~~~~~~~~~~~
/usr/include/c++/11/bits/basic_string.h:638:9: note:   template argument deduction/substitution failed:
src/api/python/bitwuzla.cpython-310-x86_64-linux-gnu.so.p/src/api/python/bitwuzla.pyx.cpp:12767:55: note:   candidate expects 3 arguments, 1 provided
12767 |     __pyx_t_4 = __Pyx_decode_cpp_string(((std::string)__pyx_t_3), 0, PY_SSIZE_T_MAX, NULL, NULL, NULL); if (unlikely(!__pyx_t_4)) __PYX_ERR(0, 382, __pyx_L1_error)
      |                                                       ^~~~~~~~~
In file included from /usr/include/c++/11/string:55,
                 from /usr/include/c++/11/bits/locale_classes.h:40,
                 from /usr/include/c++/11/bits/ios_base.h:41,
                 from /usr/include/c++/11/ios:42,
                 from src/api/python/bitwuzla.cpython-310-x86_64-linux-gnu.so.p/src/api/python/bitwuzla.pyx.cpp:1237:
/usr/include/c++/11/bits/basic_string.h:553:7: note: candidate: ‘template<class> std::__cxx11::basic_string<_CharT, _Traits, _Alloc>::basic_string(std::__cxx11::basic_string<_CharT, _Traits, _Alloc>::size_type, _CharT, const _Alloc&) [with <template-parameter-2-1> = <template-parameter-1-1>; _CharT = char; _Traits = std::char_traits<char>; _Alloc = std::allocator<char>]’
  553 |       basic_string(size_type __n, _CharT __c, const _Alloc& __a = _Alloc())
      |       ^~~~~~~~~~~~
/usr/include/c++/11/bits/basic_string.h:553:7: note:   template argument deduction/substitution failed:
src/api/python/bitwuzla.cpython-310-x86_64-linux-gnu.so.p/src/api/python/bitwuzla.pyx.cpp:12767:55: note:   candidate expects 3 arguments, 1 provided
12767 |     __pyx_t_4 = __Pyx_decode_cpp_string(((std::string)__pyx_t_3), 0, PY_SSIZE_T_MAX, NULL, NULL, NULL); if (unlikely(!__pyx_t_4)) __PYX_ERR(0, 382, __pyx_L1_error)
      |                                                       ^~~~~~~~~
In file included from /usr/include/c++/11/string:55,
                 from /usr/include/c++/11/bits/locale_classes.h:40,
                 from /usr/include/c++/11/bits/ios_base.h:41,
                 from /usr/include/c++/11/ios:42,
                 from src/api/python/bitwuzla.cpython-310-x86_64-linux-gnu.so.p/src/api/python/bitwuzla.pyx.cpp:1237:
/usr/include/c++/11/bits/basic_string.h:533:7: note: candidate: ‘template<class> std::__cxx11::basic_string<_CharT, _Traits, _Alloc>::basic_string(const _CharT*, const _Alloc&) [with <template-parameter-2-1> = <template-parameter-1-1>; _CharT = char; _Traits = std::char_traits<char>; _Alloc = std::allocator<char>]’
  533 |       basic_string(const _CharT* __s, const _Alloc& __a = _Alloc())
      |       ^~~~~~~~~~~~
/usr/include/c++/11/bits/basic_string.h:533:7: note:   template argument deduction/substitution failed:
src/api/python/bitwuzla.cpython-310-x86_64-linux-gnu.so.p/src/api/python/bitwuzla.pyx.cpp:12767:55: note:   cannot convert ‘__pyx_t_3’ (type ‘__Pyx_FakeReference<std::reference_wrapper<const std::__cxx11::basic_string<char> > >’) to type ‘const char*’
12767 |     __pyx_t_4 = __Pyx_decode_cpp_string(((std::string)__pyx_t_3), 0, PY_SSIZE_T_MAX, NULL, NULL, NULL); if (unlikely(!__pyx_t_4)) __PYX_ERR(0, 382, __pyx_L1_error)
      |                                                       ^~~~~~~~~
In file included from /usr/include/c++/11/string:55,
                 from /usr/include/c++/11/bits/locale_classes.h:40,
                 from /usr/include/c++/11/bits/ios_base.h:41,
                 from /usr/include/c++/11/ios:42,
                 from src/api/python/bitwuzla.cpython-310-x86_64-linux-gnu.so.p/src/api/python/bitwuzla.pyx.cpp:1237:
/usr/include/c++/11/bits/basic_string.h:600:7: note: candidate: ‘std::__cxx11::basic_string<_CharT, _Traits, _Alloc>::basic_string(std::__cxx11::basic_string<_CharT, _Traits, _Alloc>&&, const _Alloc&) [with _CharT = char; _Traits = std::char_traits<char>; _Alloc = std::allocator<char>]’
  600 |       basic_string(basic_string&& __str, const _Alloc& __a)
      |       ^~~~~~~~~~~~
/usr/include/c++/11/bits/basic_string.h:600:7: note:   candidate expects 2 arguments, 1 provided
/usr/include/c++/11/bits/basic_string.h:596:7: note: candidate: ‘std::__cxx11::basic_string<_CharT, _Traits, _Alloc>::basic_string(const std::__cxx11::basic_string<_CharT, _Traits, _Alloc>&, const _Alloc&) [with _CharT = char; _Traits = std::char_traits<char>; _Alloc = std::allocator<char>]’
  596 |       basic_string(const basic_string& __str, const _Alloc& __a)
      |       ^~~~~~~~~~~~
/usr/include/c++/11/bits/basic_string.h:596:7: note:   candidate expects 2 arguments, 1 provided
/usr/include/c++/11/bits/basic_string.h:592:7: note: candidate: ‘std::__cxx11::basic_string<_CharT, _Traits, _Alloc>::basic_string(std::initializer_list<_Tp>, const _Alloc&) [with _CharT = char; _Traits = std::char_traits<char>; _Alloc = std::allocator<char>]’
  592 |       basic_string(initializer_list<_CharT> __l, const _Alloc& __a = _Alloc())
      |       ^~~~~~~~~~~~
/usr/include/c++/11/bits/basic_string.h:592:45: note:   no known conversion for argument 1 from ‘__Pyx_FakeReference<std::reference_wrapper<const std::__cxx11::basic_string<char> > >’ to ‘std::initializer_list<char>’
  592 |       basic_string(initializer_list<_CharT> __l, const _Alloc& __a = _Alloc())
      |                    ~~~~~~~~~~~~~~~~~~~~~~~~~^~~
/usr/include/c++/11/bits/basic_string.h:565:7: note: candidate: ‘std::__cxx11::basic_string<_CharT, _Traits, _Alloc>::basic_string(std::__cxx11::basic_string<_CharT, _Traits, _Alloc>&&) [with _CharT = char; _Traits = std::char_traits<char>; _Alloc = std::allocator<char>]’
  565 |       basic_string(basic_string&& __str) noexcept
      |       ^~~~~~~~~~~~
/usr/include/c++/11/bits/basic_string.h:565:35: note:   no known conversion for argument 1 from ‘__Pyx_FakeReference<std::reference_wrapper<const std::__cxx11::basic_string<char> > >’ to ‘std::__cxx11::basic_string<char>&&’
  565 |       basic_string(basic_string&& __str) noexcept
      |                    ~~~~~~~~~~~~~~~^~~~~
/usr/include/c++/11/bits/basic_string.h:518:7: note: candidate: ‘std::__cxx11::basic_string<_CharT, _Traits, _Alloc>::basic_string(const _CharT*, std::__cxx11::basic_string<_CharT, _Traits, _Alloc>::size_type, const _Alloc&) [with _CharT = char; _Traits = std::char_traits<char>; _Alloc = std::allocator<char>; std::__cxx11::basic_string<_CharT, _Traits, _Alloc>::size_type = long unsigned int]’
  518 |       basic_string(const _CharT* __s, size_type __n,
      |       ^~~~~~~~~~~~
/usr/include/c++/11/bits/basic_string.h:518:7: note:   candidate expects 3 arguments, 1 provided
/usr/include/c++/11/bits/basic_string.h:500:7: note: candidate: ‘std::__cxx11::basic_string<_CharT, _Traits, _Alloc>::basic_string(const std::__cxx11::basic_string<_CharT, _Traits, _Alloc>&, std::__cxx11::basic_string<_CharT, _Traits, _Alloc>::size_type, std::__cxx11::basic_string<_CharT, _Traits, _Alloc>::size_type, const _Alloc&) [with _CharT = char; _Traits = std::char_traits<char>; _Alloc = std::allocator<char>; std::__cxx11::basic_string<_CharT, _Traits, _Alloc>::size_type = long unsigned int]’
  500 |       basic_string(const basic_string& __str, size_type __pos,
      |       ^~~~~~~~~~~~
/usr/include/c++/11/bits/basic_string.h:500:7: note:   candidate expects 4 arguments, 1 provided
/usr/include/c++/11/bits/basic_string.h:484:7: note: candidate: ‘std::__cxx11::basic_string<_CharT, _Traits, _Alloc>::basic_string(const std::__cxx11::basic_string<_CharT, _Traits, _Alloc>&, std::__cxx11::basic_string<_CharT, _Traits, _Alloc>::size_type, std::__cxx11::basic_string<_CharT, _Traits, _Alloc>::size_type) [with _CharT = char; _Traits = std::char_traits<char>; _Alloc = std::allocator<char>; std::__cxx11::basic_string<_CharT, _Traits, _Alloc>::size_type = long unsigned int]’
  484 |       basic_string(const basic_string& __str, size_type __pos,
      |       ^~~~~~~~~~~~
/usr/include/c++/11/bits/basic_string.h:484:7: note:   candidate expects 3 arguments, 1 provided
/usr/include/c++/11/bits/basic_string.h:469:7: note: candidate: ‘std::__cxx11::basic_string<_CharT, _Traits, _Alloc>::basic_string(const std::__cxx11::basic_string<_CharT, _Traits, _Alloc>&, std::__cxx11::basic_string<_CharT, _Traits, _Alloc>::size_type, const _Alloc&) [with _CharT = char; _Traits = std::char_traits<char>; _Alloc = std::allocator<char>; std::__cxx11::basic_string<_CharT, _Traits, _Alloc>::size_type = long unsigned int]’
  469 |       basic_string(const basic_string& __str, size_type __pos,
      |       ^~~~~~~~~~~~
/usr/include/c++/11/bits/basic_string.h:469:7: note:   candidate expects 3 arguments, 1 provided
/usr/include/c++/11/bits/basic_string.h:456:7: note: candidate: ‘std::__cxx11::basic_string<_CharT, _Traits, _Alloc>::basic_string(const std::__cxx11::basic_string<_CharT, _Traits, _Alloc>&) [with _CharT = char; _Traits = std::char_traits<char>; _Alloc = std::allocator<char>]’
  456 |       basic_string(const basic_string& __str)
      |       ^~~~~~~~~~~~
/usr/include/c++/11/bits/basic_string.h:456:40: note:   no known conversion for argument 1 from ‘__Pyx_FakeReference<std::reference_wrapper<const std::__cxx11::basic_string<char> > >’ to ‘const std::__cxx11::basic_string<char>&’
  456 |       basic_string(const basic_string& __str)
      |                    ~~~~~~~~~~~~~~~~~~~~^~~~~
/usr/include/c++/11/bits/basic_string.h:448:7: note: candidate: ‘std::__cxx11::basic_string<_CharT, _Traits, _Alloc>::basic_string(const _Alloc&) [with _CharT = char; _Traits = std::char_traits<char>; _Alloc = std::allocator<char>]’
  448 |       basic_string(const _Alloc& __a) _GLIBCXX_NOEXCEPT
      |       ^~~~~~~~~~~~
/usr/include/c++/11/bits/basic_string.h:448:34: note:   no known conversion for argument 1 from ‘__Pyx_FakeReference<std::reference_wrapper<const std::__cxx11::basic_string<char> > >’ to ‘const std::allocator<char>&’
  448 |       basic_string(const _Alloc& __a) _GLIBCXX_NOEXCEPT
      |                    ~~~~~~~~~~~~~~^~~
/usr/include/c++/11/bits/basic_string.h:439:7: note: candidate: ‘std::__cxx11::basic_string<_CharT, _Traits, _Alloc>::basic_string() [with _CharT = char; _Traits = std::char_traits<char>; _Alloc = std::allocator<char>]’
  439 |       basic_string()
      |       ^~~~~~~~~~~~
/usr/include/c++/11/bits/basic_string.h:439:7: note:   candidate expects 0 arguments, 1 provided
/usr/include/c++/11/bits/basic_string.h:153:7: note: candidate: ‘std::__cxx11::basic_string<_CharT, _Traits, _Alloc>::basic_string(std::__cxx11::basic_string<_CharT, _Traits, _Alloc>::__sv_wrapper, const _Alloc&) [with _CharT = char; _Traits = std::char_traits<char>; _Alloc = std::allocator<char>]’
  153 |       basic_string(__sv_wrapper __svw, const _Alloc& __a)
      |       ^~~~~~~~~~~~
/usr/include/c++/11/bits/basic_string.h:153:7: note:   candidate expects 2 arguments, 1 provided
src/api/python/bitwuzla.cpython-310-x86_64-linux-gnu.so.p/src/api/python/bitwuzla.pyx.cpp: At global scope:
src/api/python/bitwuzla.cpython-310-x86_64-linux-gnu.so.p/src/api/python/bitwuzla.pyx.cpp:8076:14: warning: ‘char* __pyx_f_8bitwuzla__to_cstr(PyObject*)’ defined but not used [-Wunused-function]
 8076 | static char *__pyx_f_8bitwuzla__to_cstr(PyObject *__pyx_v_s) {
      |              ^~~~~~~~~~~~~~~~~~~~~~~~~~
ninja: build stopped: subcommand failed.

**Comment by hanansoicher** [comment]
I also tried for a long time to get cross-compilation working with MSYS2 but ultimately gave up, I would try that again if I could get some quick guidance or insight

**Comment by mpreiner** [comment]
Can you post the full configure output? Also which version of Cython are you using?
