### ISSUE TITLE
Build fail when "./contrib/setup-symfpu.sh"

### ISSUE THREAD

**Issue by dezhangxd** [bitwuzla/bitwuzla#25]
Hi, 

The error log are listed below.

Cloning into '/home/zhangxd/bitwuzla/deps/symfpu'...
remote: Enumerating objects: 136, done.
remote: Total 136 (delta 0), reused 0 (delta 0), pack-reused 136
Receiving objects: 100% (136/136), 116.60 KiB | 0 bytes/s, done.
Resolving deltas: 100% (67/67), done.
Checking connectivity... done.
Note: checking out '8fbe139bf0071cbe0758d2f6690a546c69ff0053'.

You are in 'detached HEAD' state. You can look around, make experimental
changes and commit them, and you can discard any commits you make in this
state without impacting any branches by performing another checkout.

If you want to create a new branch to retain commits you create, you may
do so (now or later) by using -b with the checkout command again. Example:

  git checkout -b <new-branch-name>

HEAD is now at 8fbe139... Avoid an overflow in roundToIntegral in obscure formats, fix CVC4 bug 2932

This may be because there is not such a commitment.

Yours,

**Comment by andrewvaughanj** [comment]
Why do you think this is a failure? This output looks like the correct behaviour for doing a clone at a specific hash. Namely [8fbe139bf0071cbe0758d2f6690a546c69ff0053](https://github.com/martin-cs/symfpu/commit/8fbe139bf0071cbe0758d2f6690a546c69ff0053).

**Comment by dezhangxd** [comment]
Oh, Sorry for that...

**Comment by dezhangxd** [comment]
Thanks!

**Comment by aniemetz** [comment]
Yes, as @andrewvaughanj, this is the correct behavior for setting up the SymFPU dependency.
