### ISSUE TITLE
Out Of Memory killer

### ISSUE THREAD

**Issue by recoules** [bitwuzla/bitwuzla#29]
Dear developers,

We recently faced an issue using `Bitwuzla` (+ `CaDiCal` if it matters) on complex formulas like this one: [query.txt](https://github.com/bitwuzla/bitwuzla/files/8909067/query.txt).  
The process takes around ~1m30 to fill ~64GB of RAM before being killed by the operating system.

Being killed by OOM is an issue, even more when `Bitwuzla` is natively linked to the application with a binding because the latter has no chance to react.

- Is there a way for `Bitwuzla` to detect a very high memory consumption and return `unknown` before being killed? 

- I have join a query example. If you have time, you may have a look to understand why the memory consumption is so high. For comparison, `Z3` can run 2+ days without finding a solution but its memory consumption increase very slowly.

Regards,
Frédéric Recoules

**Comment by mpreiner** [comment]
Hmm on this query, Bitwuzla reports a memory usage of 128MB on my machine. Do you have issues with this specific query too?

**Comment by mpreiner** [comment]
Looks like there is something going on in the model generation. I'll have a look.

**Comment by recoules** [comment]
An additional point I forget to say is that we use model generator `-m`.

Indeed, I did not notice that without model, the solver returns almost immediately.

**Comment by aniemetz** [comment]
> I think I have tested the last version of this repo, following the README instructions:
> 
>     * setup-cadical, setup-btor
> 
>     * configure.sh then make
> 
> 
> How can I enable or disable debug build?

`./configure.sh debug`, with `./configure.sh` you built a production build (just FYI)

**Comment by recoules** [comment]
Sounds good to me. Thank you

I will update the `ocaml` binding with the most recent fixes and dependencies.
