### ISSUE TITLE
Issues when building on Windows

### ISSUE THREAD

**Issue by cnheitman** [bitwuzla/bitwuzla#30]
Hi! I'm trying to build Bitwuzla on Windows. I setup my environment as detailed in the [documentation](https://github.com/bitwuzla/bitwuzla/blob/main/docs/building_on_windows.rst). The environment seems fine, however, I'm having an issue when the [build script](https://github.com/bitwuzla/bitwuzla/blob/main/docs/building_on_windows.rst#building) tries to setup cadical. Apparently, there's an error when it applies the patch:

```
checking file src/mobical.cpp
Hunk #1 succeeded at 752 (offset 59 lines).
Hunk #2 succeeded at 1492 (offset 74 lines).
Hunk #3 succeeded at 1517 (offset 74 lines).
Hunk #4 succeeded at 1536 (offset 74 lines).
Hunk #5 succeeded at 1549 (offset 74 lines).
Hunk #6 succeeded at 1567 (offset 74 lines).
Hunk #7 succeeded at 2603 (offset 105 lines).
Hunk #8 succeeded at 2629 (offset 105 lines).
Hunk #9 succeeded at 2663 (offset 105 lines).
checking file src/resources.cpp
Hunk #1 succeeded at 20 with fuzz 2 (offset 13 lines).
Hunk #2 FAILED at 34.
Hunk #3 FAILED at 51.
Hunk #4 FAILED at 64.
Hunk #5 succeeded at 138 with fuzz 1 (offset 66 lines).
3 out of 5 hunks FAILED
checking file src/signal.cpp
Hunk #1 FAILED at 25.
Hunk #2 succeeded at 49 (offset 7 lines).
Hunk #3 FAILED at 67.
Hunk #4 FAILED at 78.
Hunk #5 FAILED at 85.
Hunk #6 succeeded at 121 with fuzz 1 (offset 18 lines).
Hunk #7 succeeded at 129 with fuzz 1 (offset 18 lines).
4 out of 7 hunks FAILED
checking file test/makefile
Hunk #1 FAILED at 1.
1 out of 1 hunk FAILED
```
In principle, it seems the patch is out of sync with the code that `./contrib/setup-cadical.sh` downloads. Could this be the case? I tried with the `main` branch as well as the tagged version (`smtcomp-2021`) and I ran into the same issue in both. Some similar happens with `btor2tools` (`picosat` and `lingeling` were setup successfully).

**Comment by aytey** [comment]
Hi, yes, this is out of sync. I'm currently in the process of updating this documentation, as I have Bitwuzla building on Windows.

The instructions will also document the need to build GMP on Windows (the currently documentation was never updated to reflect the move from Boolector to Bitwuzla).

I will try to get this done over the next week or two.

**Comment by aytey** [comment]
![image](https://user-images.githubusercontent.com/14277540/176254749-dab4f339-875f-4048-b18f-4001fc851dc3.png)

**Comment by cnheitman** [comment]
Alright, I'm looking forward to the update then.

Thanks for the quick response!

**Comment by aytey** [comment]
@cnheitman sorry for the lack of updates -- I did actually try to get these instructions revisited, but weirdly for our internal build of GCC, things work fine; however, when using an MSYS2 GCC (which is what the instructions use), I cannot break the dependency on `winpthread.dll`.

I'm still working on it, but apologies it isn't done just yet ...

**Comment by aytey** [comment]
Right, I have it building ... without too much detail: installing a MinGW via MSYS2 installed a MinGW Python -- when building CMake found the `libpython.dll` for the MinGW Python (and not the Python.org Python), which then added a dependency on the MinGW runtime (i.e., `winpthread.dll`).

I now have it setup that I can build Bitwuzla with three MinGW compilers in a way that Python.org Python can import `pybitwuzla.pyd`.

I'll get a Bitwuzla PR wrapped-up next week that documents this + the updated patches.

As a note: I've "abandoned" supporting any SAT solver that isn't CaDiCaL on Windows. I can look at resurrecting support for other solvers in time (if there's an interest/need), but the first set of instructions will only discuss building Bitwuzla with CaDiCaL.

**Comment by cnheitman** [comment]
Hi @aytey. Thanks for the update! (and going through the trouble of having it working on Windows)

Ack for the SAT solver. On my side, it does not represent an issue.

**Comment by aytey** [comment]
@cnheitman could you take a look at #31 for me?

**Comment by mpreiner** [comment]
Closing since release 0.1.0 is a complete from-scratch rewrite. Native Windows support is planned.
