### ISSUE TITLE
`define-const` not supported?

### ISSUE THREAD

**Issue by leonardoalt** [bitwuzla/bitwuzla#37]
Hi! Just tried the following example

```smt
(define-const a Int 2)
(check-sat)
```

but getting
```bash
$ bitwuzla --smt2 a.smt2
bitwuzla: a.smt2:1:2: expected command at 'define-const'
```

Anything I should be doing differently or is `define-const` not supported?

**Comment by aniemetz** [comment]
`define-const` is not SMT-LIB standard, you have to use `define-fun` for this. Note that Bitwuzla does not support `Int`.

**Comment by leonardoalt** [comment]
Ah yea, in my example there were actually no Ints, just wrote that when making the simplified version. Will use `define-fun` instead, thanks!
