### ISSUE TITLE
Cannot import pybitwuzla

### ISSUE THREAD

**Issue by WanHsuanLin** [bitwuzla/bitwuzla#39]
Hi, I would like to use the python API of bitwuzla. However, after I follow steps showing on the Github main page (Building Bitwuzla with Python Bindings), I still cannot import the pybitwuzla model. I think I have successfully build it as after the make command, it shows Built target pybitwuzla. 
Are there any extra steps required?

Thanks for you help!

**Comment by mpreiner** [comment]
Can you describe the steps you did and the error you got?

**Comment by WanHsuanLin** [comment]
Thanks for your prompt reply.
First, I compiled Btor2Tools and Kissat with -fPIC. Then, I ran the commands suggested by the readme:
./configure.sh --python
cd build
make

After make, it shows that I have successfully generated pybitwuzla. But when I ran a python program with line "from pybitwuzla import *", it showed import error "ImportError: No module named pybitwuzla"

**Comment by mpreiner** [comment]
You have to modify your `PYTHONPATH` environment variable to point to the module library in `build/lib` since there is not install target yet for the Python bindings.

```
PYTHONPATH="/absolute/path/to/build/lib" python ...
```

Please be aware that the Python bindings are still under construction and not considered stable at this point.

**Comment by WanHsuanLin** [comment]
I see. Thanks for your help!
