### ISSUE TITLE
Boolector vs Bitwuzla

### ISSUE THREAD

**Issue by recoules** [bitwuzla/bitwuzla#4]
Hi,

I was running some experiment to replace boolector by bitwuzla in our symbolic execution engine and I found that boolector is consistently faster than bitwuzla. The formulas generated are QF_ABV (because we do not need UF and do not support FP yet).

I would not generalize it (the experiments are too small with not enough variety), but here is a set of formulas ([smt2.zip](https://github.com/bitwuzla/bitwuzla/files/6704246/smt2.zip)) for which bitwuzla takes in average 20% more time than boolector on my computer.

I ran the following script to confirm my observation:
```bash
#!/bin/bash
for i in $(seq 1 10); do
    for f in $(ls xx*); do
	$1 -m -x -i < $f
    done
done
```
```bash
time ./run.sh boolector > /dev/null
```
```text
real	1m28,656s
user	1m24,222s
sys	0m4,498s
```
```bash
time ./run.sh bitwuzla > /dev/null
```
```text
real	1m46,321s
user	1m41,050s
sys	0m5,340s
```
I used boolector tag `3.2.2` and bitwuzla 95fb736.

@aniemetz @mpreiner @arminbiere Do you know from where it could come from?

**Comment by mpreiner** [comment]
@recoules  What SAT solvers did you use to build Boolector and Bitwuzla?

**Comment by recoules** [comment]
Good remark, I used cadical for both.

**Comment by mpreiner** [comment]
@recoules Do you also have benchmarks that take longer than 200ms to solve or are all your queries within this solving time?

**Comment by recoules** [comment]
@mpreiner For this specific binary, all request are solved under 100ms (but at the end, it sums up because there are 13021 queries).

**Comment by mpreiner** [comment]
Do you use the solver incrementally or do you always start from scratch and call the binary?

**Comment by recoules** [comment]
Each of the queries is run from scratch (new `execv`) (but the incremental solving is enabled to call `check-sat-assume` multiple time)

**Comment by recoules** [comment]
Here are the time I get for running 10 times the analysis (so about 10 x 254 small query sessions).

With boolector, starting from scratch + communication with pipe:
```text
real	1m40,116s
user	1m36,566s
sys	0m6,894s
```
With bitwuzla, starting from scratch + communication with pipe:
```text
real	1m57,635s
user	1m53,068s
sys	0m8,007s
```
With ocaml-bitwuzla ("native binding"), creating and deleting instance each time:
```text
real	1m57,416s
user	1m57,150s
sys	0m0,262s
```
Difference between bitwuzla versions are not significand while boolector appears to maintain its lead.
(it looks like the setup time (starting the new process + parsing the formula) is negligible with respect to solving time)

**Comment by recoules** [comment]
I do not know if it can help but here are some stats collected with `perf`:

Boolector:
```text
Performance counter stats for 'binsec -config scenario-3.conf -fml-solver boolector':

         10 474,68 msec task-clock                #    1,024 CPUs utilized          
            20 211      context-switches          #    0,002 M/sec                  
                 0      cpu-migrations            #    0,000 K/sec                  
           773 924      page-faults               #    0,074 M/sec                  
    46 273 467 553      cycles                    #    4,418 GHz                    
   110 871 806 913      instructions              #    2,40  insn per cycle         
    23 849 687 345      branches                  # 2276,890 M/sec                  
       227 879 101      branch-misses             #    0,96% of all branches        

      10,228322399 seconds time elapsed

       9,773868000 seconds user
       0,798961000 seconds sys
```

Bitwuzla:
```text
Performance counter stats for 'binsec -config scenario-3.conf -fml-solver bitwuzla':

         12 180,43 msec task-clock                #    1,020 CPUs utilized          
            20 241      context-switches          #    0,002 M/sec                  
                 2      cpu-migrations            #    0,000 K/sec                  
           841 767      page-faults               #    0,069 M/sec                  
    54 001 380 844      cycles                    #    4,433 GHz                    
   130 556 346 387      instructions              #    2,42  insn per cycle         
    27 690 065 004      branches                  # 2273,324 M/sec                  
       285 436 830      branch-misses             #    1,03% of all branches        

      11,936210695 seconds time elapsed

      11,353133000 seconds user
       0,931947000 seconds sys
```

OCaml Bitwuzla:
```text
Performance counter stats for 'binsec -config scenario-3.conf -fml-solver bitwuzla -sse-native-solver':

         11 692,97 msec task-clock                #    1,000 CPUs utilized          
                52      context-switches          #    0,004 K/sec                  
                 0      cpu-migrations            #    0,000 K/sec                  
            27 316      page-faults               #    0,002 M/sec                  
    52 191 356 711      cycles                    #    4,463 GHz                    
   134 501 722 158      instructions              #    2,58  insn per cycle         
    29 467 098 608      branches                  # 2520,070 M/sec                  
       327 202 340      branch-misses             #    1,11% of all branches        

      11,693825005 seconds time elapsed

      11,645303000 seconds user
       0,048005000 seconds sys
```
I am very surprised (in the wrong way) that even while significantly reducing the number of context-switches and page-faults, the overall performance is the same with native binding compared to creating a new process. I know that the Caml binding has a cost, but I do not know why there is so many branch-misses (+15%).


PS: this binsec version is an experimental one and is not the one released on github

**Comment by mpreiner** [comment]
@recoules A large chunk of the runtime goes into model generation in these examples. For example for xx254 (~500ms in total), about  (~300ms) is spent in model generation. I just pushed some optimizations that considerably reduce the model generation time on your benchmarks. On the xx254 example it is now 15ms instead of >300ms.

$ time ./run.sh bitwuzla > /dev/null
   
real    4m54.493s
user    4m33.498s
sys     0m20.625s

$ time boolector > /dev/null
                                                                                                                                                                
real    5m22.030s
user    5m1.761s
sys     0m19.929s

(tested with both solvers using the same CaDiCaL version)

**Comment by recoules** [comment]
@mpreiner Sweet! Thank you very much, now native binding has some interest (~25% gain for this example) :-)

Here are the stats for the scenario 1 (exhaustive path enumeration), so about 13k queries. 

Boolector bin:
```text
real	7m8,332s
user	6m54,199s
sys	0m36,741s
```
Bitwuzla bin:
```text
real	5m37,832s
user	5m21,138s
sys	0m40,456s
```
OCaml Bitwuzla:
```text
real	4m8,480s
user	4m7,907s
sys	0m0,456s
```

This issue can be closed.

**Comment by mpreiner** [comment]
Awesome!
