### ISSUE TITLE
Stuck rewriting in rewrite_eq_exp

### ISSUE THREAD

**Issue by jix** [bitwuzla/bitwuzla#42]
When using bitwuzla as backend for [yosys-smtbmc](/YosysHQ/yosys), I encountered an input for which bitwuzla hangs essentially forever during the initial rewrite for a `(define-fun ...)`, even before the following `(check-sat)` is issued. I manually minimized the yosys-smtbmc generated SMT2 by removing everything unnecessary to trigger this behavior. I then reduced the width of the involved signals from 32 to 24 bits. With 24 bits, it does get past the `(define-fun ...)` but still takes 30 seconds just to process it. Both variants are attached. When I take a stack trace during the rewriting, I see deeply nested `rewrite_eq_exp` calls. I tested with the latest main version of bitwuzla.

I also filed a corresponding issue for boolector boolector/boolector#205 which shows exactly the same behavior with an identically named function in the stack trace, so I assume the issue is with code that is common to both solvers.

[hang_min_32.smt2.txt](https://github.com/bitwuzla/bitwuzla/files/10210141/hang_min_32.smt2.txt)
[hang_min_24.smt2.txt](https://github.com/bitwuzla/bitwuzla/files/10210142/hang_min_24.smt2.txt)

**Comment by mpreiner** [comment]
Thanks for the bug report, we'll have a look!

**Comment by aniemetz** [comment]
I just noticed that the attempted fix did not entirely fix the issue. I'll investigate.
