### ISSUE TITLE
beta_reduce segfault w/ reduced 'update' node

### ISSUE THREAD

**Issue by ndrewh** [bitwuzla/bitwuzla#43]
Getting a segfault in `bzla_sort_fun_get_codomain` when `beta_reduce` calls `bzla_node_create_apply`: https://github.com/bitwuzla/bitwuzla/blob/2bb1fe653e7b3f7ea7ffff8d803f98769ca3f46b/src/bzlabeta.c#L443-L452

Backtrace:
(sorry, no symbols, debug build runs too slow & i'm hitting this really deep in a incremental solve so I don't have an easy reproducer). 
```
#0  0x00007ffff68eb3b1 in bzla_sort_fun_get_codomain () from /usr/local/lib/libbitwuzla.so
#1  0x00007ffff689e118 in new_node () from /usr/local/lib/libbitwuzla.so
#2  0x00007ffff68a1c45 in create_exp.constprop () from /usr/local/lib/libbitwuzla.so
#3  0x00007ffff68a3560 in bzla_node_create_apply () from /usr/local/lib/libbitwuzla.so
#4  0x00007ffff687462d in beta_reduce () from /usr/local/lib/libbitwuzla.so
#5  0x00007ffff6973cbb in bzla_eliminate_applies () from /usr/local/lib/libbitwuzla.so
#6  0x00007ffff697fa91 in bzla_simplify () from /usr/local/lib/libbitwuzla.so
#7  0x00007ffff688cf12 in bzla_check_sat () from /usr/local/lib/libbitwuzla.so
#8  0x00007ffff6945b0b in bitwuzla_check_sat () from /usr/local/lib/libbitwuzla.so
...
```

Relevant snippet from `new_node`:
https://github.com/bitwuzla/bitwuzla/blob/2bb1fe653e7b3f7ea7ffff8d803f98769ca3f46b/src/bzlanode.c#L2734-L2737

This requires `e[0]` to have a function sort, but in the crashing case, it doesn't. Thus, it segfaults when trying to access `sort->fun.codomain->id`.

In the case of the crash, the function being applied is actually a `BZLA_UPDATE_NODE`, which seems like a totally legal type to apply. However, the update node's array (`e[0]`) is somehow actually a `BZLA_BV_CONST_NODE`, which means (of course) the sort does not have a codomain. I know only very little about this code, but this seems pretty suspicious. I'm only using the public C API, which seems to have thorough checks on the types, so I don't think I'm feeding in garbage here. My array is just 16-bit bv => 8-bit bv.

This reproduced repeatedly with the same backtrace, so it doesn't seem like any sort of one-off memory corruption. My best guess is for some sequence of array operations, it's possible for a BZLA_UPDATE_NODE to have its array (function) to be reduced entirely to a constant (though, this seems suspicious). I noticed some other code that avoids eliminating lambdas when the parent requires them, and I added a check against `bzla_node_is_update`, and this fixes it. However I have no idea if this is the right fix, or if there is something deeper going on here. I will post a reproducer if I can make one.

```diff
diff --git a/src/bzlabeta.c b/src/bzlabeta.c
index f338a52..8f54991 100644
--- a/src/bzlabeta.c
+++ b/src/bzlabeta.c
@@ -379,7 +379,8 @@ beta_reduce(Bzla *bzla,
        * generation for extensionality */
       else if (bzla_node_is_lambda(real_cur) && cur_parent
                && (bzla_node_is_fun_eq(cur_parent)
-                   || bzla_node_is_fun_cond(cur_parent)))
+                   || bzla_node_is_fun_cond(cur_parent)
+                   || bzla_node_is_update(cur_parent) ))
       {
         assert(!bzla_node_param_get_assigned_exp(real_cur->e[0]));
         cur_lambda_depth--;
@@ -464,6 +465,7 @@ beta_reduce(Bzla *bzla,
              * as argument */
             if (cur_parent
                 && (bzla_node_is_fun_eq(cur_parent)
+                    || bzla_node_is_update(cur_parent)
                     || (bzla_node_is_fun_cond(cur_parent)
                         && !bzla_node_param_get_assigned_exp(real_cur->e[0]))))
             {
```

**Comment by mpreiner** [comment]
@ndrewh Thanks for the bug report and sorry for the slow response. We are currently working on a complete rewrite of Bitwuzla and this will not be an issue anymore in the future.
