### ISSUE TITLE
check-model does nothing in release build

### ISSUE THREAD

**Issue by matthewsot** [bitwuzla/bitwuzla#52]
Not sure if this is intentional, but while debugging #51 I noticed that `check-model` seems to be a nop in release mode. I think this is because `assert`ions get stripped in release mode, and `cm.check()` is wrapped in an `assert` here:  https://github.com/bitwuzla/bitwuzla/blob/main/src/solving_context.cpp#L57C24-L57C24

To reproduce:
```
$ vim src/check/check_model.cpp
... insert a return false; at top of CheckModel::check() ...
$ ./configure.py release
$ meson compile
$ ./src/main/bitwuzla -m --check-model
(check-sat)
sat
^D
$ cd ..
$ ./configure.py debug
$ meson compile
$ ./src/main/bitwuzla -m --check-model
(check-sat)
bitwuzla: ../src/solving_context.cpp:57: bzla::Result bzla::SolvingContext::solve(): Assertion `cm.check()' failed.
Aborted (core dumped)
```

Not sure what the intended behavior is here; I noticed that `check-model` defaults to `false` on release builds, but if it is indeed a nop maybe it should just be disabled as an option for release ?

**Comment by mpreiner** [comment]
Checking models was initially only intended as debug option and was enclosed in a #ifndef NDEBUG block. Seems like I forgot to change the assertion part. Thanks for reporting, we'll fix this.

**Comment by matthewsot** [comment]
Makes a lot of sense, thanks for the response!
