### ISSUE TITLE
Is it possible to force output format in new version?

### ISSUE THREAD

**Issue by iVoider** [bitwuzla/bitwuzla#54]
I'd like to force dec output format like in boolector with option -d.
BTOR_OPT_OUTPUT_NUMBER_FORMAT has no effect.

**Comment by aniemetz** [comment]
Configuring the output number format for bit-vector values is now possible. Via the command line, this can be configured with `--bv-output-format`. For changes in the API that allow to configure this, see https://github.com/bitwuzla/bitwuzla/blob/main/NEWS.md. For examples, see https://github.com/bitwuzla/bitwuzla/blob/main/examples/c/print.c and https://github.com/bitwuzla/bitwuzla/blob/main/examples/cpp/print.cpp. Python API will follow.
