### ISSUE TITLE
re-bound lets

### ISSUE THREAD

**Issue by TrevorHansen** [bitwuzla/bitwuzla#59]
I'm experimenting to understand "let binding" in smtlib better and have crafted a case which I think Bitwuzla is handling incorrectly:

```
(set-info :smt-lib-version 2.6)
(set-logic QF_BV)
(set-info :license "https://creativecommons.org/licenses/by/4.0/")
(set-info :category "crafted")
(set-info :status sat)

; variables get bound twice
(assert 
	(let 
		(
			(x (_ bv1 6) ) 
		)
		(let 
			(
				(x (_ bv0 6))  
				(y x)
			)
			(not (= x y)) 
		)
	)
)
(check-sat)
```
I'm not entirely sure if this is allowed - Mathsat gives an error. But checking the specification I didn't notice anything prohibiting it.

**Comment by mpreiner** [comment]
Hi @TrevorHansen, thanks for the bug report! Bitwuzla has indeed an issue here, the problem should be sat, but Bitwuzla reports unsat since the parser seems to ignore the shadowing of x here.

**Comment by aniemetz** [comment]
@TrevorHansen yep, same cause, thanks again!
