### ISSUE TITLE
Some unit tests fail unless bitwuzla is built with assertions

### ISSUE THREAD

**Issue by BrunoDutertre** [bitwuzla/bitwuzla#61]
I've tried this:
```
./configure.py --testing
cd build
meson compile
meson tesst
```
Some of the tests fail. The statistics show:
```
Ok:                 3763
Expected Fail:      0   
Fail:               10  
Unexpected Pass:    0   
Skipped:            0   
Timeout:            0 
```

In the test logs, the failures are all `failed to die` or `died but not with expected error`.

All the tests pass if we build with assertions. So it looks like the `ASSERT_DEATH` tests should
be skipped when assertions are disabled?

**Comment by mpreiner** [comment]
Thanks @BrunoDutertre, death tests that depend on assertions to fail are now disabled for non-debug builds.
