### ISSUE TITLE
Set RUNPATH when installing into custom dir given by --prefix

### ISSUE THREAD

**Issue by fbrausse** [bitwuzla/bitwuzla#62]
As is customly done, Bitwuzla's configure.py script allows installing into a non-standard location via `--prefix`. It will also install a pkg-config file bitwuzla.pc in there. For ESBMC I'm using this setup with Bitwuzla installed into a custom directory, but due to `libbitwuzla.so` linking to the other libs without providing a RUNPATH entry to find them, I'm getting
```
src/esbmc/esbmc: error while loading shared libraries: libbitwuzlabb.so: cannot open shared object file: No such file or directory
```
See also <https://github.com/esbmc/esbmc/issues/1302>.

Over at Meson, in https://github.com/mesonbuild/meson/issues/4027#issuecomment-486796316 (the issue has been fixed in v0.55) I've seen that it seems that it might be possible to include `-Wl,-rpath,${libdir}` or similar into the pkg-config file and I'm wondering whether that would be a viable approach for the configure script to do when Bitwuzla is being installed into a custom prefix.

If not, please feel free to close this issue and we'll try to deal with it on our side somehow.

**Comment by mpreiner** [comment]
Thanks for report! I'll have a look.

**Comment by mpreiner** [comment]
@fbrausse This now fixed on the main branch. There was no need to add the rpath to the pkg-config file. Setting the rpath for the libraries solved the issue.

**Comment by fbrausse** [comment]
@mpreiner Many thanks, that help a lot!
