### ISSUE TITLE
reference bitwuzla show undefined symbol error

### ISSUE THREAD

**Issue by cctv130** [bitwuzla/bitwuzla#64]
Hi  my friends, I referenced this project in the triton project. When I used import triton, the following error was prompted

triton.cpython-311-x86_64-linux-gnu.so: undefined symbol: _ZN4bzla9BitVector7from_siEmlb

This seems to make me generate a bitwuzla so file, but I followed the steps of the official website and only generated *.A file. How do I fix this error

**Comment by mpreiner** [comment]
When Python bindings are involved, you have to build a shared library. If you configure with `--python` this will happen automatically. If you want to build shared libraries only, then configure with `./configure.py --shared`.

**Comment by cctv130** [comment]
> When Python bindings are involved, you have to build a shared library. If you configure with `--python` this will happen automatically. If you want to build shared libraries only, then configure with `./configure.py --shared`.

thank you
