### ISSUE TITLE
Parser quietly failing

### ISSUE THREAD

**Issue by SimonKlx** [bitwuzla/bitwuzla#65]
Hello, i upgraded to the newest bitwuzla version and the parser seems to quietly fail for certain cases.

I was not able to pin point exactly what causes the error but a small example that seems to reproduce the problem would be:

```
(set-logic QF_ABV)
(declare-fun a () (_ BitVec 1))
(declare-fun b () (_ BitVec 1))
(declare-fun c () (_ BitVec 1))
(declare-fun d () (_ BitVec 1))

(assert (= #b1 (bvnot (ite (= (concat (bvxor (bvor (bvand a c) (bvand b (bvnot c))) (bvand (bvxor c d) c)) (bvnot (bvxor c d))) (bvsub (concat a c) (concat b d))) (_ bv1 1) (_ bv0 1)))))

(check-sat)
```

If i paste this into a file and run `bitwuzla -p <input_file>` i get the following output:
`(set-logic ALL)
(check-sat)
(exit)`

I do not get an error an using the cpp parser interface also returns an empty error message string.

**Comment by mpreiner** [comment]
I'm not entirely sure why you'd expect this to fail? It looks like Bitwuzla is able to solve the problem via preprocessing, i.e., in this case the assertion is simplified to true, which is omitted when printing the formula.

**Comment by aniemetz** [comment]
It seems that @SimonKlx interpreted this as a "quiet parser failure", but indeed it is not, as @mpreiner said. This just indicates that the formula was already simplified to true via preprocessing.

**Comment by SimonKlx** [comment]
Thank you for the quick answer! It seems there was a misunderstanding on my behalf.
First i did not know that this formula automatically evaluates to true.
Second i was not aware that there is this preprocessing step and expected the output of the -p option to look more or less like my smt input. So i was confused and assumed the parser failed when i got this "empty" looking output containing no variables and even a different logic string.
Thank you for your time and looking into this!
