### ISSUE TITLE
Support for input file language option

### ISSUE THREAD

**Issue by casseyh** [bitwuzla/bitwuzla#75]
Currently the solver binary only supports passing input files with extension .smt2 or .btor2 (see [here](https://github.com/bitwuzla/bitwuzla/blob/d0b98ca844d983c053b7cbf4427fdf11dcfb0e04/src/main/options.cpp#L367)). If the file ends with neither extension, it assumes the file is a command line option (seems like a bug?).

```
$ bitwuzla problem.txt
[error] invalid option 'problem.txt'

$ bitwuzla problem.smt2
sat
```

It would be nice to have an additional option similar to Z3 (-smt2) or CVC5 (--lang smt2) to indicate the language of the problem being passed without relying on the file extension.

Thanks!

**Comment by mpreiner** [comment]
The new `--lang` option is now pushed to main. Further, by default Bitwuzla now assumes that the input file is in smt2, so in your above case you don't even need the `--lang smt2` option. If the file ends with suffix `.btor2`, Bitwuzla will still expect the file to be in BTOR2 format, which can be however overridden with the `--lang` option.
