### ISSUE TITLE
Symbol names don't follow SMTLIB2 

### ISSUE THREAD

**Issue by baierd** [bitwuzla/bitwuzla#77]
Hi,

i've noticed that symbol names that use characters not allowed by [SMTLIB2 standard](http://smtlib.cs.uiowa.edu/papers/smt-lib-reference-v2.6-r2021-05-12.pdf) (3.2 Symbols) are not automatically quoted by Bitwuzla.
Example: `main::a` should be returned as ``|main::a| or `main a` as `|main a|`.
Currently, the names are not changed at all, technically breaking SMTLIB2 printouts.

Thank you for your help!

Best,
Daniel

**Comment by baierd** [comment]
A more complete example:
```
    (set-logic ALL)
    (declare-const main a Bool)
    (declare-const b Bool)
    (push 1)
    (assert (xor main a b))
```
expected to contain:
    `(declare-const |main a| Bool)`

**Comment by aniemetz** [comment]
@baierd This is not valid SMT-LIB, and thus rejected by Bitwuzla. If you use characters that are not allowed in regular symbols, you have to explicitly use the "|...|" notation.

**Comment by baierd** [comment]
I completely agree that it should be rejected by Bitwuzla, it is not however. I can create symbols with those names. I argue that i should not be able to :D

**Comment by aniemetz** [comment]
Ah, that makes more sense. I agree that we should wrap such symbols.
