### ISSUE TITLE
Parser ignores boolean check-sat flag if check-sat in query

### ISSUE THREAD

**Issue by baierd** [bitwuzla/bitwuzla#78]
Hi,

i've noticed that the parser ignores the Boolean "check-sat" flag if a `(check-sat)` is present in the query.
From the API and description (`const char* bitwuzla_parser_parse(BitwuzlaParser* parser, bool parse_only);`) i would expect that a `(check-sat)` is ignored if the bool is set to true.
Is this intentional?

I can provide an example if you need one.

Thank you for your help.
Best,
Daniel

**Comment by aniemetz** [comment]
I cannot reproduce, it behaves as intended for me (and yes, if `parse_only` is `true`, `(check-sat)` calls are not issued). Can you provide an example that fails for you?

**Comment by baierd** [comment]
Since i currently can't find the query in question i will close this issue until i can find it again. Sorry for the inconvenience. I will reopen the issue once i find the example that i had a while back.
