### ISSUE TITLE
Pass a buffer with SMT-LIB to bitwuzla_parser_new

### ISSUE THREAD

**Issue by ligurio** [bitwuzla/bitwuzla#79]
Bitwuzla API describes an example that demonstrate how to pass a file in SMT-LIB format to bitwuzla parser [^1]:

```c
  BitwuzlaOptions* options = bitwuzla_options_new();
  FILE* infile = fopen("../smt2/quickstart.smt2", "r");
  BitwuzlaParser* parser = bitwuzla_parser_new(
      options, "../smt2/quickstart.smt2", infile, "smt2", 2, "<stdout>");
```

I have an SMT-LIB in a `char *` buffer, and currently it is not possible to pass buffer directly to `bitwuzla_parser_new` without using `fmemopen()` [^2]. It would be nice to have the ability to pass a buffer directly to Bitwuzla parser.

[^1]: https://bitwuzla.github.io/docs/c/types/bitwuzlaparser.html#_CPPv419bitwuzla_parser_newP15BitwuzlaOptionsPKcP4FILEPKc
[^2]: https://man7.org/linux/man-pages/man3/fmemopen.3.html

**Comment by nils1603** [comment]
Hey there,

any news on this? We just stumbled across the same problem and this would be a really helpful addition!

Thanks :)

**Comment by aniemetz** [comment]
@nils1603 thanks for checking i! No news yet, we've been too swamped the last couple of months but finally have a bit more room to breath. We will address this shortly.

**Comment by aniemetz** [comment]
Parsing from string is now supported on main. See https://github.com/bitwuzla/bitwuzla/blob/main/examples/c/parse.c, https://github.com/bitwuzla/bitwuzla/blob/main/examples/cpp/parse.cpp and https://github.com/bitwuzla/bitwuzla/blob/main/examples/python/parse.py for examples. Note that the C++ API also allows to parse from an input stream.
