### ISSUE TITLE
Terms/Sorts can not be used on threads distincs to the thread they were created in

### ISSUE THREAD

**Issue by baierd** [bitwuzla/bitwuzla#86]
Hi,

Terms/Sorts can not be used on threads that are distinct to the thread they are created in.
The source of this seems to be the `thread_local` Term/Sort storage (and possible other `thread_local` usages).

Would it be possible to fix this, so that Terms/Sorts can be used on any arbitrary thread?
(Note: i am not talking about multi-threaded solving)

Best,
Daniel

**Comment by baierd** [comment]
An example would be this small program:
```
#include <stdio.h>
#include <stdlib.h>
#include <pthread.h>
#include "include/bitwuzla/c/bitwuzla.h"

struct args {
    Bitwuzla* instance;
    BitwuzlaTerm term;
};

void *myThreadFun(void *vargp) {
    printf("Thread started\n");
    BitwuzlaTerm term = ((struct args*)vargp)->term;
    bitwuzla_term_is_true(term);                     // Crash
    printf("Thread finished without issues\n");
    return NULL; 
}
   
int main() { 
    pthread_t thread_id; 

    BitwuzlaOptions *options = bitwuzla_options_new();
    bitwuzla_set_option(options, BITWUZLA_OPT_PRODUCE_MODELS, 1);
    Bitwuzla *bitwuzla = bitwuzla_new(options);
    BitwuzlaTerm tru = bitwuzla_mk_true();

    printf("Before Thread\n");

    struct args *arguments = (struct args *)malloc(sizeof(struct args));
    arguments->term = tru;

    pthread_create(&thread_id, NULL, myThreadFun, arguments);
    pthread_join(thread_id, NULL);

    exit(0);
}
```

**Comment by mpreiner** [comment]
We have similar issues with the OCaml bindings.  We are currently investigating possible solutions to this problem, but there is no easy fix. It will very likely require changes in the API and (lots of) internal refactoring. We'll keep you posted on the progress.

**Comment by baierd** [comment]
Thank you very much!
This is currently the most important problem holding our group back in using Bitwuzla.

**Comment by mpreiner** [comment]
@baierd The refactor of the term manager is now done and merged to main.
