### ISSUE TITLE
Perfomance deterioration from OCaml binding vs process

### ISSUE THREAD

**Issue by recoules** [bitwuzla/bitwuzla#9]
I faced a strange situation where a "*big*" part of an array is initialized (~1kB) but not used in any assertion (e.g. this [formula](https://github.com/bitwuzla/bitwuzla/files/7697122/formula.txt)). If I feed the SMT file to the solver (`bitwuzla -m -i`), it solves it quickly but, if I build the formula from the OCaml api, the solving time is multiplied by 10 (only considering the time of `check-sat` query).

So, using the C API, would you say that creating "*junk*" expressions that are not involved in any assertion can slowdown the resolution? Is there a way that a term is processed even if it is not part of the assertions? 
Of course, the problem may come from the OCaml binding itself or even the way I build the formula.
Still, the build takes less time than sending the formula through pipe, so I do not know what I could have messed.

------

I know the situation can be avoided here with a simple preprocessing but we will not always be able to say that the array initialization is not required. Another approach we are using is laziness: we do not initialize the array, but if the solver return `sat`, we check for each address returned in the model that it does not conflict with the initialization. If there is a conflict, we add an assertion `(= (select array address) value)` and query the solver again (mode incremental). The number of bytes sent can be tuned to avoid doing too many loops in the worst case where each initialized byte were meaningful.

Do you have some ideas, with the knowledge of solver internals, of other techniques we can use to deal with big initialized arrays?

**Comment by recoules** [comment]
I am able to reproduce the slowdown directly from C API but it sound that it is only because I set `BITWUZLA_OPT_PRODUCE_MODELS` to `2`.

Yet, I am not sure what is the purpose of the level `2` against `1` because it sounds like I am still able to query the value assignment of an expression that does not appear in assertions when using `1`  (in fact, it is just evaluating the term with random/any values for symbols that are not in the model).

Here is the program I used:
- `L = 1` is quick whatever `N`
- `L = 2` is quick for small  `N`
- `L = 2` is slow for `N = 1024` for instance
```c
#include <stdlib.h>
#include <stdio.h>
#include <time.h>
#include <bitwuzla.h>

#define N 1024
#define L 1

int main (int argc, char *argv[])
{
  Bitwuzla *bitwuzla = bitwuzla_new();
  bitwuzla_set_option(bitwuzla, BITWUZLA_OPT_PRODUCE_MODELS, L);
  bitwuzla_set_option(bitwuzla, BITWUZLA_OPT_INCREMENTAL, 1);

  const BitwuzlaSort *bv8 = bitwuzla_mk_bv_sort(bitwuzla, 8);
  const BitwuzlaSort *bv32 = bitwuzla_mk_bv_sort(bitwuzla, 32);
  const BitwuzlaSort *ar32_8 = bitwuzla_mk_array_sort(bitwuzla, bv32, bv8);

  const BitwuzlaTerm *a = bitwuzla_mk_const(bitwuzla, ar32_8, "a");
  const BitwuzlaTerm *x = bitwuzla_mk_const(bitwuzla, bv32, "x");

  const BitwuzlaTerm *c2  = bitwuzla_mk_bv_value_uint64(bitwuzla, bv32, 2);
  const BitwuzlaTerm *c50 = bitwuzla_mk_bv_value_uint64(bitwuzla, bv32, 50);

  const BitwuzlaTerm *z = a;
  const BitwuzlaTerm *k = bitwuzla_mk_bv_value_uint64(bitwuzla, bv32, 4198400);
  for (int i = 0; i < N; i += 1) {
    const BitwuzlaTerm *v = bitwuzla_mk_bv_value_uint64(bitwuzla, bv8, i ^ N);
    z = bitwuzla_mk_term3(bitwuzla, BITWUZLA_KIND_ARRAY_STORE,
			  z,  k, v);
    k = bitwuzla_mk_term1(bitwuzla, BITWUZLA_KIND_BV_INC, k);
  }

  bitwuzla_assert(bitwuzla,
		  bitwuzla_mk_term2(bitwuzla,
				    BITWUZLA_KIND_AND,
				    bitwuzla_mk_term2(bitwuzla,
						      BITWUZLA_KIND_BV_UGE,
						      x, c2),
				    bitwuzla_mk_term2(bitwuzla,
						      BITWUZLA_KIND_BV_ULE,
						      x, c50)));

  clock_t start = clock();
  BitwuzlaResult r = bitwuzla_check_sat(bitwuzla);
  clock_t end = clock();
  switch (r) {
  case BITWUZLA_SAT:
    printf("sat");
    break;
  case BITWUZLA_UNSAT:
    printf("unsat");
    break;
  case BITWUZLA_UNKNOWN:
    printf("unknown");
    break;
  }
  printf(" (%ld tiks)\n", end - start);

  printf("value of z[50] = %s\n",
	 bitwuzla_get_bv_value(bitwuzla,
			       bitwuzla_mk_term2(bitwuzla,
						 BITWUZLA_KIND_ARRAY_SELECT,
						 z, c50)));

  bitwuzla_delete(bitwuzla);
  return 0;
}
```

**Comment by mpreiner** [comment]
@recoules I'll have a look, but this will take some time since I'm currently swamped with other stuff.

**Comment by recoules** [comment]
@mpreiner It is less of an issue now I know that `BITWUZLA_OPT_PRODUCE_MODELS` level 1 allow me to do everything I need (was thinking that solver would fail if I query the value of an arbitrary expression).

**Comment by mpreiner** [comment]
Closing since release 0.1.0 is a complete from-scratch rewrite.
