### ISSUE TITLE
/usr/bin/ld: cannot find -lgmp: No such file or directory

### ISSUE THREAD

**Issue by Phongvngg1** [bitwuzla/bitwuzla#99]
help, idk why

root@fedora:~/bitwuzla/build# ninja install
[194/195] Linking target src/main/bitwuzla
FAILED: src/main/bitwuzla 
c++  -o src/main/bitwuzla src/main/bitwuzla.p/main.cpp.o src/main/bitwuzla.p/options.cpp.o src/main/bitwuzla.p/time_limit.cpp.o -Wl,--as-needed -Wl,--no-undefined -Wl,-O1 -Wl,-rpath,XXXXXXXXXXXXXXXX -Wl,--start-group src/libbitwuzla.a src/lib/libbitwuzlabb.a src/lib/libbitwuzlabv.a src/lib/libbitwuzlals.a -static -pthread -lgmp -lgmp -lgmp -lgmp -Wl,--end-group
/usr/bin/ld: cannot find -lgmp: No such file or directory
/usr/bin/ld: cannot find -lgmp: No such file or directory
/usr/bin/ld: cannot find -lgmp: No such file or directory
/usr/bin/ld: cannot find -lgmp: No such file or directory
collect2: error: ld returned 1 exit status
ninja: build stopped: subcommand failed.

**Comment by mpreiner** [comment]
Do you have a static version of gmp installed on your system?

**Comment by mpreiner** [comment]
Closed due to inactivity.

**Comment by maroneze** [comment]
Note for future readers: on Fedora 42, I also had to manually install a static version of mpfr, and since there's no `mpfr-static` package, I had to [download the .tar.gz](https://www.mpfr.org/mpfr-current/) from MPFR's website, then compile and install it, so that bitwuzla might find it.
